/***********************************************************************/
/*                                                                     */
/*  FILE        :hwinit.c                                              */
/*  DATE        :Wed, May 09, 2012                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
         



#include "iodefine.h"
#ifdef __cplusplus
extern "C" {
#endif
extern void hw_initialise(void);
#ifdef __cplusplus
}
#endif


void hw_initialise(void)
{
// Initialize routine
/*
  P1DDR = 0;
  P1DR.BYTE = 0;
  P1DR.BIT.B7 = 1;
  P1DR.BIT.B6 = 1;
  P1DR.BIT.B5 = 1;
  P1DR.BIT.B4 = 1;
  P1DR.BIT.B3 = 1;
  P1DR.BIT.B2 = 1;
  P1DR.BIT.B1 = 1;
  P1DR.BIT.B0 = 1;
*/
}
