/***********************************************************************/
/*                                                                     */
/*  FILE        :inthandler.c                                          */
/*  DATE        :Wed, May 09, 2012                                     */
/*  DESCRIPTION :Interrupt Handler                                     */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
     


												
#include "inthandler.h"

//  vector 1 Reserved

//  vector 2 Reserved

//  vector 3 Reserved

//  vector 4 Reserved

//  vector 5 Reserved

//  vector 6 Reserved

//  vector 7 NMI
void INT_NMI(void) { }
//  vector 8 TRAP
void INT_TRAP1(void) { }
//  vector 9 TRAP
void INT_TRAP2(void) { }
//  vector 10 TRAP
void INT_TRAP3(void) { }
//  vector 11 TRAP
void INT_TRAP4(void) { }
//  vector 12 IRQ0
void INT_IRQ0(void) { }
//  vector 13 IRQ1
void INT_IRQ1(void) { }
//  vector 14 IRQ2
void INT_IRQ2(void) { }
//  vector 15 IRQ3
void INT_IRQ3(void) { }
//  vector 16 IRQ4
void INT_IRQ4(void) { }
//  vector 17 IRQ5
void INT_IRQ5(void) { }
//  vector 18 Reserved

//  vector 19 Reserved

//  vector 20 WOVI
void INT_WOVI(void) { }
//  vector 21 CMI
void INT_CMI(void) { }
//  vector 22 Reserved

//  vector 23 ADI
void INT_ADI(void) { }
//  vector 24 IMIA0
//void INT_IMIA0(void) { }
//  vector 25 IMIB0
//void INT_IMIB0(void) { }
//  vector 26 OVI0
void INT_OVI0(void) { }
//  vector 27 Reserved

//  vector 28 IMIA1
//void INT_IMIA1(void) { }
//  vector 29 IMIB1
void INT_IMIB1(void) { }
//  vector 30 OVI1
void INT_OVI1(void) { }
//  vector 31 Reserved

//  vector 32 IMIA2
//void INT_IMIA2(void) { }
//  vector 33 IMIB2
//void INT_IMIB2(void) { }
//  vector 34 OVI2
void INT_OVI2(void) { }
//  vector 35 Reserved

//  vector 36 CMIA0
void INT_CMIA0(void) { }
//  vector 37 CMIB0
void INT_CMIB0(void) { }
//  vector 38 CMIA1B1
void INT_CMIA1B1(void) { }
//  vector 39 TOVI0_1
void INT_TOVI0_1(void) { }
//  vector 40 CMIA2
void INT_CMIA2(void) { }
//  vector 41 CMIB2
void INT_CMIB2(void) { }
//  vector 42 CMIA3B3
void INT_CMIA3B3(void) { }
//  vector 43 TOVI2_3
void INT_TOVI2_3(void) { }
//  vector 44 DEND0A
void INT_DEND0A(void) { }
//  vector 45 DEND0B
void INT_DEND0B(void) { }
//  vector 46 DEND1A
void INT_DEND1A(void) { }
//  vector 47 DEND1B
void INT_DEND1B(void) { }
//  vector 48 Reserved

//  vector 49 Reserved

//  vector 50 Reserved

//  vector 51 Reserved

//  vector 52 ERI0
//void INT_ERI0(void) { }
//  vector 53 RXI0
//void INT_RXI0(void) { }
//  vector 54 TXI0
//void INT_TXI0(void) { }
//  vector 55 TEI0
//void INT_TEI0(void) { }
//  vector 56 ERI1
//void INT_ERI1(void) { }
//  vector 57 RXI1
//void INT_RXI1(void) { }
//  vector 58 TXI1
//void INT_TXI1(void) { }
//  vector 59 TEI1
//void INT_TEI1(void) { }
//  vector 60 ERI2
//void INT_ERI2(void) { }
//  vector 61 RXI2
//void INT_RXI2(void) { }
//  vector 62 TXI2
//void INT_TXI2(void) { }
//  vector 63 TEI2
//void INT_TEI2(void) { }


