/***********************************************************************/
/*                                                                     */
/*  FILE        :Rx_3069.c                                             */
/*  DATE        :Mon, May 27, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
         
#include"Rx_protcol.h"
#include "iodefine.h"
#include "intrinsic.h"
#include"sci.h"
#include"fm_tx.h"


int RX(void){
	rx_init();												//初期化関数。rx_protocol_inv.cで定義　み
//	debug_puts("*");
	check_rx_working();
	if(FX_DET != 0){										//DETがONの時にだけ読み取るようにする
		int errint;											//データ受信＆デコード時のエラー検出に使う。　み
		P5DDR = 0xff;
		errint = get_data();								/*データの受信とデコードを行う。errint = 0ならば正常受信、1ならばプリアンブル検出エラー。　み*/
		if(errint==0){										//正常にデータが取れた場合　み
			debug_puts("Getting Data is Succeeded.\r\n");	//（）内の文字列を送信　み
			delay_ms(300);									//300ms待つ	み
			free(uplink_rx_buff);							//uplink_rx_buffで確保した領域を離す　み
			free(info);										//infoで確保した領域を離す　み
			return 1;										//正常時の処理おしまい　み
		}
		else{												//エラー検出の場合　み
			free(uplink_rx_buff);							//uplink_rx_buffで確保した領域を離す　み
			free(info);
		}													//エラー検出時の処理おしまい　み    
	}
	return 1;
}															//メイン関数おしまい　み

void check_rx_working(void){
	debug_puts("[");
	debug_putdec(FM_mode);
	debug_puts(",");
	debug_putdec(DT_mode);
	debug_puts("]");
}
	




