/***********************************************************************/
/*                                                                     */
/*  FILE        :typedefine.h                                          */
/*  DATE        :Wed, May 09, 2012                                     */
/*  DESCRIPTION :Aliases of Integer Type                               */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
         


typedef signed char _SBYTE;
typedef unsigned char _UBYTE;
typedef signed short _SWORD;
typedef unsigned short _UWORD;
typedef signed int _SINT;
typedef unsigned int _UINT;
typedef signed long _SDWORD;
typedef unsigned long _UDWORD;
